# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/bruno/proyectos/github/qftshell/qftshell/ui/OpenConnection.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_OpenConnection(object):
    def setupUi(self, OpenConnection):
        OpenConnection.setObjectName("OpenConnection")
        OpenConnection.resize(312, 201)
        OpenConnection.setSizeGripEnabled(True)
        OpenConnection.setModal(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(OpenConnection)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(OpenConnection)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.lineEdit = QtWidgets.QLineEdit(OpenConnection)
        self.lineEdit.setObjectName("lineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit)
        self.label_2 = QtWidgets.QLabel(OpenConnection)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.serialPort = QtWidgets.QComboBox(OpenConnection)
        self.serialPort.setObjectName("serialPort")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.serialPort)
        self.label_3 = QtWidgets.QLabel(OpenConnection)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.speed = QtWidgets.QComboBox(OpenConnection)
        self.speed.setObjectName("speed")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.speed)
        self.label_4 = QtWidgets.QLabel(OpenConnection)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.flowControl = QtWidgets.QComboBox(OpenConnection)
        self.flowControl.setObjectName("flowControl")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.flowControl)
        self.verticalLayout.addLayout(self.formLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 68, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.buttonBox = QtWidgets.QDialogButtonBox(OpenConnection)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(OpenConnection)
        QtCore.QMetaObject.connectSlotsByName(OpenConnection)

    def retranslateUi(self, OpenConnection):
        _translate = QtCore.QCoreApplication.translate
        OpenConnection.setWindowTitle(_translate("OpenConnection", "Open Connection..."))
        self.label.setText(_translate("OpenConnection", "Name"))
        self.label_2.setText(_translate("OpenConnection", "Serial Port"))
        self.label_3.setText(_translate("OpenConnection", "Speed"))
        self.label_4.setText(_translate("OpenConnection", "Flow Control"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    OpenConnection = QtWidgets.QDialog()
    ui = Ui_OpenConnection()
    ui.setupUi(OpenConnection)
    OpenConnection.show()
    sys.exit(app.exec_())
